### ISSUE TITLE
Second-order reaction-diffusion dynamical system

### ISSUE THREAD

**Issue by spinang** [genn-team/genn#115]
Good evening,
I'm trying to implement the following second order dynamical system:
![cattura](https://cloud.githubusercontent.com/assets/11614831/20755927/17a9d784-b711-11e6-93e3-2a0102f82bc1.PNG)
where:
![codecogseqn](https://cloud.githubusercontent.com/assets/11614831/20755568/bcb8d20e-b70f-11e6-9683-4f8a39018c44.gif)
I've modeled the system in such a way every parameter is a state variable and until now I've implemented the reactive part of the system only, i.e. the state equations in which the terms due to the epsilon quantity are absent. Moreover, subscripts a and b are referred to two neurons coupled together.

My main difficult lies in how to realize the diffusive term, that is the additive contribution to the first state equation of each neuron. Purely reactive neurons are not exactly spiking neurons, but when mu, s and both biases i1 and i2 are properly set, a limit cycle with slow-fast dynamics can be obtained. 

How can I carry out the output due to the first state variable of a neuron towards the second state equation of the other?

**Comment by tnowotny** [comment]
I assume at some point you will use more than just 2 units? Otherwise using a GPU is slightly pointless.
Assuming that you want many units, I would proceed to define the internal dynamics of each unit in the "simCode" snippet, then define a synapse type with an "evntThreshold" snippet that is always true, i.e.
```
weightUpdateModel synapsemodel;
synapsemodel.evntThreshold="1";
```
Furthermore, you would want to set the synaptic activation as 
```
synapsemodel.simCodeEvnt="$(s)=$(eps)*tanh(2.0*$(x1_pre))";
```
and a post-synaptic model that does nothing:
```
postSynModel postsyn;
postsyn.postSyntoCurrent="$(s)";
```
Of course, it depends how you would like to handle if there are several units interacting; you may want to consider putting the tanh into the postsyn model.
----
If you just want two units, I would make a single unit of it with 4 variables.

**Comment by spinang** [comment]
Thanks for your quick reply.
But, what does `$(x1_pre)` mean?

**Comment by tnowotny** [comment]
I was assuming that your variables would be called `x1` and `x2`.

**Comment by spinang** [comment]
How can I use a neuron variable from simCodeEvnt?

**Comment by tnowotny** [comment]
neuron variables are available in synapse code with postfix `_pre` and `_post`.
So, if you want the variable `y1` of the pre-synaptic neuron, you write `y1_pre` in any synaptic code snippet.
Same for `_post` and post-synaptic neuron variables.

**Comment by spinang** [comment]
Wonderful, it works perfectly.
Thanks a lot for your help.
