### ISSUE TITLE
Error: unsupported CUDA device major version: 6

### ISSUE THREAD

**Issue by hanwentao** [genn-team/genn#136]
Error occurred when running `userproject/testprojects.sh` (for both *development* branch and *2.2.2* tag):

```
...
g++ -std=c++11 -Wall -Wextra -DNVCC=\""/usr/local/cuda-8.0/bin/nvcc"\" -DMODEL=\"/home/hanwentao/snn/genn/userproject/MBody1_project/model/MBody1.cc\" -o /home/hanwentao/snn/genn/userproject/MBody1_project/model/generateALL /home/hanwentao/snn/genn/lib/src/generate*.cc -I"/home/hanwentao/snn/genn/lib/include" -I"/usr/local/cuda-8.0/include" -L"/home/hanwentao/snn/genn/lib/lib" -L"/usr/local/cuda-8.0/lib64" -lgenn -lcuda -lcudart
call was ./generateALL /home/hanwentao/snn/genn/userproject/MBody1_project/model
optimizing block size...
Error: unsupported CUDA device major version: 6
genn-buildmodel.sh:75: error 50: command failure
ERROR: Following call failed with status 12800:
cd model && genn-buildmodel.sh MBody1.cc && make clean all SIM_CODE=MBody1_CODE
Exiting...
```

Development environment:

* GPU: GeForce GTX 1080
* Linux: Ubuntu 16.04.2
* CUDA: 8.0.44-1

**Comment by tnowotny** [comment]
This looks like the previous issue where a new major device version is rejected by default rather than tolerated by default. It is a bit silly - we should swap this to default acceptance as they typically are backward compatible for GeNN. (and just assume characteristics haven't changed hugely wrt blocksize optimization) @jamesturner246, do you remember what to do (it is in the block size optimization bit).

**Comment by tnowotny** [comment]
This should now have been resolved in the latest development branch.
Let us know if you are still experiencing problems.

**Comment by hanwentao** [comment]
Yes, it works now.
