### ISSUE TITLE
Is it necessary to call modelDefinition in user code?

### ISSUE THREAD

**Issue by whenov** [genn-team/genn#139]
In most examples in `userproject` except `SynDelay_project`, `modelDefinition` is explicitly called in user code. But in the tutorial and `SynDelay_project`, `modelDefinition` is not called.

Why all of them run correctly? Which one is the right way?

**Comment by jamesturner246** [comment]
As documented, the only time `modelDefinition` needs to be run is when the generateALL binary is loaded, when generating the source files. The user doesn't need to call it anywhere. The example projects call it again in user code because they use the initialised `NNmodel` model object for other purposes.

**Comment by whenov** [comment]
Thanks for your explanation!

On Mon, Mar 20, 2017 at 5:00 AM, James Paul Turner <notifications@github.com
