### ISSUE TITLE
The refractory of Poisson neuron potentially suffers from floating-point underflow

### ISSUE THREAD

**Issue by whenov** [genn-team/genn#183]
https://github.com/genn-team/genn/blob/6ef4f370c00120d4469a39e948027c75677f269a/lib/src/neuronModels.cc#L107

If `t` with `float` type grows large enough, its value (as well as the value of `spikeTime`) will become imprecise due to arithmetic underflow, which can affect the evaluation of the refractory period condition.

**Comment by neworderofjamie** [comment]
Apologies for not getting back to you - you are entirely correct. I think in general using floating point times (rather than counting timesteps) is not a good idea - it doesn't take many hours of simulation to get to the point where single-precision floating point is unable to add the timestep to simulation time.

Assuming 24-bits of accuracy and that dt=1ms my calculation is that adding dt to t will cease to make any difference at 2^24÷1000÷60÷60 = 4.66 hours. @tnowotny  what do you think? Using 32-bit unsigned integer timesteps would give you a somewhat safer 2^32÷1000÷60÷60 = 1193 hours :)

**Comment by tnowotny** [comment]
Hi - I fully agree. At some point there was the idea to base things on a variable ```iT``` (integer Time) but I fear it might not have permeated fully ... ```iT``` is typically still converted back to ```t``` when time is needed in equations ...

**Comment by neworderofjamie** [comment]
integer time is the 'master' and ``t`` is calculated off it in ``stepTimeCPU`` and ``stepTimeGPU`` but ``t`` will end up pretty meaningless after only a few hours e.g. try compiling:

```cpp
#include <iostream>

#include <cstdint>

int main()
{
    const uint32_t sixHours = 6 * 60 * 60 * 1000;
    const uint32_t nextTimestep = sixHours + 1;

    const float sixHoursFloat = (float)sixHours;
    const float nextTimestepFloat = (float)nextTimestep;
    
    std::cout << nextTimestepFloat - sixHoursFloat << std::endl;
    return 0;
}
```
I guess we should:

1. substitute ``iT`` into generated code 
2. add ``sIT`` or something to keep track of the last spike time for STDP in integer form
3. update built-in models to use ``sIT`` and ``iT`` in any time-based logic
4. add a warning to encourage users to move away from relying on ``t`` and ``sT``

@whenov - If you're still interested in contributing to GeNN this might be a good place to start! I would be more than happy to point you at the bits of code you would need to modify.

**Comment by tnowotny** [comment]
exactly what I was thinking ...

**Comment by neworderofjamie** [comment]
The solution I suggested ended up being very awkward to implement so, instead in #207 we added the option to support double-precision time.
