### ISSUE TITLE
Generated makefile issues on Mac OS X

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#239]
``-Wl,-rpath=$(GENERATED_CODE_DIR)`` doesn't seem to work and, more generally, $(CXX) is not being set to clang

**Comment by alexdewar** [comment]
Does it matter if ``$(CXX)`` is explicitly set to clang or not? I thought ``make`` would find clang, or does it always default to using gcc?

Re the ``-rpath`` problem, I did have a similar issue with a newer version of gcc. It seems that the rpath property at least for ELF binaries is deprecated so I had to pass ``--disable-new-dtags`` as well otherwise gcc just silently ignored it.

**Comment by alexdewar** [comment]
See: https://stackoverflow.com/questions/7967848/use-rpath-but-not-runpath

**Comment by neworderofjamie** [comment]
That is a good question - my understanding is that, on mac, clang will emulate a very elderly GCC (4.2ish) for backward compatibility but you need to override ``$(CXX)`` to use clang properly (as we do for GeNN).

The second issue turns out to be because for whatever reason clang doesn't parse the = in the rpath directive (which isn't present in the makefile for our automatic tests which **do** pass on Mac...) :scream:
