### ISSUE TITLE
Drop upper numpy version requirement

### ISSUE THREAD

**Issue by jamesturner246** [genn-team/genn#299]
Would it be reasonable (safe) to drop PyGeNN's upper version requirement on numpy, or at least keep it up to date?

Reason being pip gets funny when I try installing pygenn after tensorflow, since it requires numpy>=1.16.0,<2.0.

On a related note, can pygenn be made into a wheel, so pip can handle that more intelligently?

**Comment by neworderofjamie** [comment]
So, the issue with the numpy version was related to some package (I *vaguelly* remember it was neo) pulled in by PyNN and hence by PyNN GeNN. If you/@chanokin could check that the PyNN version PyNN GeNN pulls in has been fixed to work with latest numpy then I'm totally happy to remove this (it's in various Jenkinsfiles as well as setup.py as setup.py itself requires numpy in order to build the native extensions). 

Yes is the answer - if you look at the [GeNN releases](https://github.com/genn-team/genn/releases), wheels for PyGeNN are now included. The only issue is that the wheel system doesn't have a good way to manage non-python dependency versions like CUDA so the wheels are tied to whatever version of CUDA was used to build them (I think TensorFlow has this issue too I think)

**Comment by chanokin** [comment]
PyNN goes for anything above or equal to Numpy 1.8.2

https://github.com/NeuralEnsemble/PyNN/blob/ac96bf59f6b0a4778cf4ed186544ee215423205b/setup.py#L126

Neo needs 1.10.0 and above but really hates version 1.16.0

https://github.com/NeuralEnsemble/python-neo/blob/39c14da8286e760a0643687f8fdc7fceb2d2c012/setup.py#L8

I guess we can safely change Numpy versions to what Neo requires

**Comment by neworderofjamie** [comment]
Ahh, was it specifically 1.16.1 that didn't work with neo? If so, feel free to remove the upper limit (unless there's some sort of 'not 1.
16.1' version string you can use)

**Comment by chanokin** [comment]
`'numpy>=1.10.0,!=1.16.0'` is what they use we surely can change for `'numpy>=1.10.0,!=1.16.*'`

**Comment by neworderofjamie** [comment]
ooh nice, that would be perfect, between the two of you can you apply that liberally to all the setup.pys and Jenkinsfiles and make P.R.s?

**Comment by jamesturner246** [comment]
#301
