### ISSUE TITLE
undefined reference to `memcpy@GLIBC_2.14'

### ISSUE THREAD

**Issue by TheSalocin** [genn-team/genn#360]
When trying to run the example model via ./generate_run test1 I get the following error:

> ../x86_64-conda_cos6-linux-gnu/bin/ld: MBody1_CODE/librunner.so: undefined reference to `memcpy@GLIBC_2.14'

It runs fine with the --cpu-only flag.

I've got cuda version 11.0 on Ubuntu 18.04 with gcc version 8.4.0

**Comment by neworderofjamie** [comment]
From your path it looks like your using the compiler provided by Anaconda - in general this doesn't work with CUDA. You should use the standard GCC that comes with Ubuntu 18.0t.

**Comment by TheSalocin** [comment]
Yes, you were right. Removing the conda gcc compiler fixed it. Sadly I didn't find a way to keep the compiler and force conda to use the standard one

**Comment by mstimberg** [comment]
> Yes, you were right, thank you. Removing the conda gcc compiler fixed it. Sadly I didn't find a way to keep the compiler and force conda to use the standard one

Sorry for jumping into this issue late but just to comment on this. The Anaconda compilers are selected because they set the relevant environment variables. You should be able to keep them installed, but temporarily unset the variables. Unfortunately, there are quite a number of them (and I'm not 100% sure which of them are taken into account by GeNN/nvcc). I'd at least unset `CXX`, `CXXFLAGS`, `CPP`, `CPPFLAGS`, `GCC`.
