### ISSUE TITLE
Got 'error: duplicate parameter name' when ./generate_run test in userproject/Izh_sparse_project

### ISSUE THREAD

**Issue by luyi256** [genn-team/genn#416]
I'm using genn-4.4.0. After entering userproject/Izh_sparse_project, use `make` and `./generate_run test`, I got
```
/home/xxxx/genn/genn-4.4.0/userproject/Izh_sparse_project/model/IzhSparse_CODE/definitionsInternal.h(164): error: duplicate parameter name

1 error detected in the compilation of "/tmp/tmpxft_0002235d_00000000-6_neuronUpdate.cpp1.ii".
optimizeBlockSize: NVCC failed
genn-buildmodel.sh:88: error 50: command failure
ERROR: Following call failed with status 12800:
cd model && genn-buildmodel.sh IzhSparse.cc && make -j 56 clean all
Exiting...
```
My OS is Linux Ubuntu, CUDA version is 10.1. I think it may be a little bug in genn. 
Thanks for your help.

**Comment by neworderofjamie** [comment]
Thanks for this bug report. Sadly, the only workaround right now is not to use the built-in ``FixedNumberPost`` connector (which the IzhSparse model does).

The underlying issue is the result of a name conflict between the ``FixedNumberPost`` connector parameter "rowLength" and the merged structure field used to store the row length. Similar class of issue to #385 and similarly the solution is to go through and put underscores in front of all internally-generated variables etc.

**Comment by beenleyi** [comment]
@neworderofjamie Got it, thanks a lot.

**Comment by neworderofjamie** [comment]
This is a legitimate bug so I'd like to keep it open!

**Comment by neworderofjamie** [comment]
This parameter has been renamed to "num"
