### ISSUE TITLE
More information from ``SWIG::DirectorMethodException``

### ISSUE THREAD

**Issue by neworderofjamie** [genn-team/genn#450]
These get thrown (and since #433 caught!) when errors happen in Python callbacks called from C++ using SWIG directors e.g. derived parameter calculation code. However, the code generated by SWIG to throw the exceptions looks like:

```c++
PyObject *error = PyErr_Occurred();
if (error) {
  Swig::DirectorMethodException::raise("Error detected when calling 'DerivedParamFunc.__call__'");
}
```

So the _contents_ of the error i.e. the message is totally ignored (meaning that, until I dug into this I was worried something was really wrong with this code but infact I had just forgotten to ``import numpy``...). Extra code can be monkey-patched into the exception throwing code with (from google):

```c++
%feature("director:except") {
    if( $error != NULL ) {
      PyObject *ptype, *pvalue, *ptraceback;
      PyErr_Fetch( &ptype, &pvalue, &ptraceback );
      PyErr_Restore( ptype, pvalue, ptraceback );
      PyErr_Print();
      Py_Exit(1);
    }
  }
```
which prints out a standard Python error message. However I'm not really sure what all the ``PyErr_Fetch`` and ``PyErr_Restore`` business does and I'd rather pipe the errors back into an exception message or something but, that is definitely beyond my Python C API understanding (@alexdewar any thoughts as a more experienced Python C API wrangler?)

**Comment by alexdewar** [comment]
I *think* the way to do it would be to convert ``pvalue`` to a Python string (which should include the type name, message and stack trace) and then C++-ify that:
https://stackoverflow.com/questions/37684153/convert-exception-error-to-string
https://stackoverflow.com/questions/5356773/python-get-string-representation-of-pyobject

If it turns out to be a faff I guess you could always dig into pybind11 and see what magic they're using.
