### ISSUE TITLE
Define NMDA-resepror postsynaptic model

### ISSUE THREAD

**Issue by mohamad-qodosi** [genn-team/genn#455]
Hi. thank you for your amazing work.
I'm trying to implement a decision making model (wang 2002) using PyGenn library.
this model uses LIF neurons and synapses has AMPA, GABA and NMDA receptors.
AMPA and GABA was easily implemented using ExpCond model but i'm having a hard time defining NMDA receptors. here is a differential equation for these receptors:
![image](https://user-images.githubusercontent.com/23719357/132983633-c05f89e3-fe0e-4f19-a2c7-007dc18281f0.png)
![image](https://user-images.githubusercontent.com/23719357/132983637-7295d099-41ba-49fd-962c-419c50c0bdc3.png)

I used `create_custom_postsynaptic_class`  function to define my new receptor. also variable x acts like normal ExpCond model so I used same formula for that and used `$(inSyn)` to store x value.

here is my code:
```
NMDA = create_custom_postsynaptic_class(
    class_name='NMDAR',
    param_names=['Mg', 'tau_raise', 'tau_decay', 'alpha', 'E'],
    var_name_types=[('S', 'scalar')],
    derived_params=[('expRaise', create_dpf_class(lambda pars, dt: np.exp(-dt / pars[1]))()),
                    ('coefDecay', create_dpf_class(lambda pars, dt: -dt / pars[2])())],
    decay_code='$(inSyn) *= $(expRaise);',
    apply_input_code='$(S) += $(S) * $(coefDecay) + $(alpha) * $(inSyn) * DT * (1 - $(S));' +
                     '$(Isyn) += $(inSyn) * ($(E) - $(V)) / (1 + $(Mg) * exp(-0.062 * $(V) / 3.57));'
)
```

as I said, I have used `$(inSyn)` as x in formula and I have additional S variable.
and when I want to use it, my code is like:
`
    model.add_synapse_population('DE1_DE1_NMDA', 'DENSE_GLOBALG', synapse_delay,
                                 E1_pop, E1_pop,
                                 StaticPulse(), {}, {'g': g_pyramidal_NMDA * w_positive}, {}, {},
                                 NMDA, synapse_postsyn_NMDA_var, {'S': 0})`
note that I have about 12 synapses like this.

but when I run my code, when It wants to build the model, there is some errors:
`./wang2002_CODE/neuronUpdateCUDAOptim.cc(401): error: expression must be a modifiable lvalue

./wang2002_CODE/neuronUpdateCUDAOptim.cc(404): error: class "MergedNeuronUpdateGroup3" has no member "SInSyn0"

./wang2002_CODE/neuronUpdateCUDAOptim.cc(404): error: identifier "lpsS" is undefined
`
and In this errors, the capital S is from my variable name (if I change my var name to P, errors will be `PInSyn0` and `lpsP`
could you help me to solve this problem?

**Comment by neworderofjamie** [comment]
Can you try using ``DENSE_GLOBALG_INDIVIDUAL_PSM`` when you call ``add_synapse_population``? I think, for backward-compatibility reasons, ``DENSE_GLOBALG`` tries to optimise out postsynaptic model variables as well as weights. 

I'm not familiar with this model but, assuming C<sub>E</sub> is number of excitatory inputs, shouldn't ``S`` and ``x`` be presynaptic rather than postsynaptic variables? If so you would need to pair a custom postsynaptic update model which implement I<sub>rec,NMDA</sub> with a custom weight update model doing _something_ like this (totally untested):
```python
NMDARWU = create_custom_weight_update_class(
    class_name='NMDAR_WU',
    param_names=['tau_raise', 'tau_decay', 'alpha'],
    var_name_types=[('g', 'scalar')],
    pre_var_name_types=[("S", "scalar"), ("x", "scalar")],
    derived_params=[('expRaise', create_dpf_class(lambda pars, dt: np.exp(-dt / pars[0]))()),
                    ('coefDecay', create_dpf_class(lambda pars, dt: -dt / pars[1])())],
    sim_code="$(addToInSyn, $(g) * $(S));",
    pre_spike_code="""
        $(x) += 1.0;
        """,
    pre_dynamics_code="""
        $(x) *= $(expRaise);
        $(S) += $(S) * $(coefDecay) + $(alpha) * $(x) * DT * (1 - $(S));
        """)
```
Which should be pretty efficient as the presynaptic dynamic get implemented in the presynaptic neuron kernel. See http://genn-team.github.io/genn/documentation/4/html/d5/d24/sectSynapseModels.html#wum_pre_post_dynamics for reference.

**Comment by mohamad-qodosi** [comment]
thank you. `DENSE_GLOBALG_INDIVIDUAL_PSM` solved the issue but there is still a problem with my code because I cant regenerate original paper results.

I'm not a biologist (I'm a computer programmer) but I think receptors are on postsynaptic neuron dendrite. that's why I implemented them as postsynaptic class. but I think your codes makes more sense. I will test that. I think the weight_update_class you wrote is the whole thing I need. I think using this I don't need a special post synaptic class. just a normal current. am I right?

I have another silly question if you don't mind. I was using `population.spike_count` and Its shape was (1, 1) but as soon as I used my population as a pre-synaptic population, the shape changed to (1, 26) which was odd. now I have replaced it with `len(population.current_spikes)` and I have no problem but It was strange for me.

**Comment by neworderofjamie** [comment]
I'm definitely not a biologist either _but_, the sums over ``j`` in your systems of equations are over the (presynaptic) inputs to the neuron. If the dynamics are linear (like AMPA), they can be applied to the _sum_ of the inputs rather than to each input individually but, in the case of non-linear synapse models (like NMDA), this optimisation isn't valid (see section 2.2 of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2638500/ for a better explanation).

Are you using delays in your model? If so each neuron stores the spikes it's emitted over the maximum delay number of timesteps. ``NeuronGroup.spike_count`` gives direct access to this data but, that isn't generally useful so you should always use ``NeuronGroup.current_spikes``.

**Comment by mohamad-qodosi** [comment]
thank you so much. you helped me a lot.
