### ISSUE TITLE
Indentation in user-defined code snippets

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#46]
The first line is aligned with the indentation of the generated code but the other lines don't. This makes the generated code a bit ugly but there are no functional problems.

**Comment by tnowotny** [comment]
A possible solution is to post-process the entire generated code for tabbing.

**Comment by neworderofjamie** [comment]
#150 indents user-defined code to match the surrounding generated code (as long as within the user-defined code it doesn't have its own weird indentation)

**Comment by tnowotny** [comment]
Wouldn't it be trivial to just strip whitespace from user code?

**Comment by neworderofjamie** [comment]
the problem is, it's totally valid for user code to have it's own indenting around ifs or whatever so if you stripped off all leading whitespace you'd have to then fully parse the user code and re-indent it. At least for now I think leaving the internal indentation of the user code up to the authors is alright.

**Comment by neworderofjamie** [comment]
If it was as simple as detecting {} and indenting it would be ok but { and } are also used for arrays and weird C++ 11 array constructors.

**Comment by tnowotny** [comment]
right ... never mind. I didn't think it through ;-)
