### ISSUE TITLE
Avoiding creating unused variables

### ISSUE THREAD

**Issue by esinyavuz** [genn-team/genn#47]
I'm renaming this thread as we have other instances of unused variable type of problems and it would be nice to take care of this in a more systematic way during code generation.

The previous thread consisted of the warnings on:
Unused variable warning for ipost, ipre for GLOBALG used with NSYNAPSE model

This happens in the SynDelay project. It is not as straightforward as it seems; indexing is not necessary when we use GLOBAL, but if we had a synapse model with a variable that uses these indices they would be needed. These are just warnings at the moment, but it would be more elegant to make a proper check. 

Another example of this kind of problem is unnecessary post-to-pre arrays for sparse connectivity. They are (presumably) not needed unless the learning kernel is used.

Creating unnecessary variables would fill the memory unnecessarily and we should avoid this.

**Comment by tapaswenipathak** [comment]
Hi @esinyavuz: Can I work on the ticket?

**Comment by neworderofjamie** [comment]
Hi @tapaswenipathak,

I'm afraid @esinyavuz has left the project, but you're more than welcome to work on this ticket. GeNN's code generator has been somewhat refactored since this issue was created so this is less of an issue but, looking through our build server's output, the following two unused variables are definitely still being created by GeNN's CUDA backend:

1. ``shSpk`` created [here](https://github.com/genn-team/genn/blob/master/src/genn/backends/cuda/backend.cc#L523) - as well as the existing tests, this should only be created if any of the synapse groups have their ``m_SpanType`` set to ``SynapseGroup::SpanType::POSTSYNAPTIC``
2. ``synAddress`` created [here](https://github.com/genn-team/genn/blob/master/src/genn/backends/cuda/presynapticUpdateStrategy.cc#L281) - this is rather more tricky as it depends upon whether ``$(id_syn)`` is referenced in the subsequently generated code.

**Comment by tapaswenipathak** [comment]
Thanks for the notes @neworderofjamie.

**Comment by tapaswenipathak** [comment]
@neworderofjamie: No `synAddress` can be removed as per me, can you take a look?
