### ISSUE TITLE
Refine global - register -global transfers

### ISSUE THREAD

**Issue by tnowotny** [genn-team/genn#55]
within the learn code, there can be repeated reference to dd_remapXX[iprePos]. Whenever it is used more than once, it would probably be efficient to fetch it into a local register.

**Comment by tnowotny** [comment]
1. load dd_remapXX[...] into a register by default.
2. But more generally, introduce an annotation "readonly XXX YYY" e.g. ``readonly scalar x;`` for variables. Those would not be written back to global memory; the register copy could be declared ``const``

**Comment by tapaswenipathak** [comment]
Hi folks: Is this ticket still open?

**Comment by neworderofjamie** [comment]
Well, the read-only part has been implemented by #247 and the equivalent of ``dd_remap[iprepos]`` is now loaded into a register [here](https://github.com/genn-team/genn/blob/master/src/genn/backends/cuda/backend.cc#L696). The issue is that that is done whether it is required or not as discussed in #248

**Comment by tapaswenipathak** [comment]
All PRs are there then right, can you ref the ticket in the PRs?
