### ISSUE TITLE
Interface GeNN - embedded system

### ISSUE THREAD

**Issue by Crypto1993** [genn-team/genn#70]
Good evening everybody.
I am returned here to discuss with you about GeNN and in particular I'd like to ask you if GeNN allows the creation of "downloadable" models inside embedded systems.

Let me explain: in our laboratory we have some robots which have been created using differents parts. Some components are obviously electronic boards and/or embedded systems (like the PC104), that drive the entire systems. Before we used GeNN for our tests and simulations, we used to control our robots via an homemade architecture based on Visual Studio 2008: the application loaded a DLL file generated by another Visual Studio solution and therefore it controlled the system. Now, my question is the following: can GeNN allow the creation of a DLL file (or something else) which can be downloaded in an embedded system? More generally speaking: is it possible interfacing GeNN with such systems (for instance, calling the model in a C program which drives motors, sensors and other stuff)?

**Comment by jamesturner246** [comment]
Hi Crypto1993.

I don't see why not. GeNN just provides the source of the model. It's up to the user how he / she wishes to compile it (executable, static lib, shared lib). Obviously the CUDA hardware must be accessible to the embedded system, like in the Jetson TX1 chips, or a wrapper lib must be written to to handle data transfer to the CUDA node.

James.

**Comment by Crypto1993** [comment]
I'm asking you this because in Visual Studio is relatively simple to include an external DLL file.
I would like to make an example: consider a robot able to acquire some images from a FishEye cam; if for each image a meaning is associated (for example, an image representing a T stands for "turn left"), the robot should learn a sequence, but also it should be able to avoid some disturbances during the execution of the sequence itself (for example, imagine there's a new T image appearing during the execution of the sequence; if this one is acquired, then the stored sequence won't be correct more). Now, the network should be able to allow to the robot both learning and interfacing with the electronic/mechanical parts, since almost each movement is associated to a result produced by the network.

This is a brief description of the work I should do. I'll give you more details if required.

**Comment by tnowotny** [comment]
I agree with James, there is no reason why this should not work. There are two ways of doing the integration:
a) you take the generated code from GeNN and include it in your main control software for the robot. If it can link against CUDA and has access to an NVIDIA GPU, this should work nicely. But even if not, the "GPU_ONLY" version we are beta-testing in the development branch should still work.
b) it should be possible to compile the generated code into a library rather than an executable and link it to the main control code later. This would need some fiddling with the Makefiles, obviously. Again, the library would additionally link to CUDA and would need access to an NVIDIA GPU in order to work (unless the CPU_ONLY version is invoked).
