### ISSUE TITLE
Rolling all tools/gen_*_syns executables into a single synapse creation tool in lib/bin/

### ISSUE THREAD

**Issue by jamesturner246** [genn-team/genn#75]
As the title says, we seem to have a lot of executables in the tools dir which all do similar things, but with some specific fixed parameters:

gen_pnlhi_syns
gen_kcdn_syns
gen_kcdn_syns_fixto10k
gen_pnkc_syns
gen_pnkc_syns_indivID
gen_syns_sparse
gen_syns_sparse_izhModel

I propose adding a more general-purpose connectivity file creation tool inside lib/bin instead, with options for sparse, individID, etcetera, to make feature addition and maintenance a bit simpler, and make the tools a bit more flexible in general.

Thoughts?
James.

**Comment by esinyavuz** [comment]
I agree that it is getting a bit out of control but if we do this we need to keep in mind the differences in design principles of different models. For example in the Izhikevich example we fix the number of connections per neuron to a value, which is then shared between different synapse populations for that single neuron. Therefore we have one single file (gen_syns_sparse_izhModel) to create the connectivity between inhibitory and excitatory neuron populations. On the contrary, mushroom body models use different files to create connectivity between different populations (hence different files for pnkc and kcdn).

In principle `gen_syns_sparse.cc` should be general enough to create a single synapse population, given the number of presynaptic and postsynaptic neuron, connection probability and the jitter. It also generates the all-to-all array, therefore it should be possible to use it for dense connectivity types as well. We can add the `individualID` option to this one and make it more general.

**Comment by jamesturner246** [comment]
Aggree that gen_syns_sparse is general. There is the possibility of passing a command line option to fix the number of connections per neuron. for example:

./genn_connectivity -n 100

which could limit the number of connections per-neuron to 100, or something similar.

**Comment by tnowotny** [comment]
In principle this looks like a promising way of cleaning up BUT I would not want to put a general tool into the main GeNN directory (lib/bin) and so make it a part of GeNN. In my mind, all these tools are user-side and we do not provide a tools to solve it all because a new user is guaranteed to want yet something else again (and they should!). 
In summary, if you want to make the user-side examples more pretty that's fine by me but please do not make it core GeNN business. That kind of would move us backwards into the era of pre-defined model types.

**Comment by esinyavuz** [comment]
@jamesturner246 , it wouldn't work to create a single population like that because we fix the number of connections per neuron with all the other populations, therefore we need to create all the network at once.

We could rename `gen_syns_sparse.cc` and make it more explicit that this code can be used to create this particular type of random connectivity. But I agree with @tnowotny , making this type of tools core functions make people believe that this is the only type of connectivity supported...

**Comment by tnowotny** [comment]
This is now outdated. There is support for users to build connectivities within genn and additional tools for building connectivity etc are "userspace".
