### ISSUE TITLE
SPARSE connectivity

### ISSUE THREAD

**Issue by spinang** [genn-team/genn#89]
Good evening to everybody.
I would to describe you an idea I got recently...
Probably, you remember an old post I wrote about the STDP learning and, in particular, about the fact that even without a time instant t_post at which my post-synaptic neuron fired the conductance of the synapse increased. If you remember, you suggested me to check if the plot of g with respect to gRaw was effectively a sigmoidal function (it was) and other stuff, but it seems that it depends all on the rule that was implemented. Ok, that's not the problem.

Now, I'm supposing a population X of two simple Izhikevich neurons in which the current is not the accumulator iSyn, but it is a variable I that I defined by myself (as a new state variable that is not integrated during the execution). In this way, I can manipulate it during the simulation. Since the problem discussed in my old post I cited before is still unsolved, I decide to create a fictitious neuron of a different population that is connected to only one of the two neurons of the first population via a NSYNAPSE connection. Even this neuron is an Izhikevich neuron with variable current.

I had a look on the Izh_sparse_project but I can't understand how the sparse connectivity works practically (I've already read the reference manual, but it seems there's no a simple example), because I would to connect my fictitious neuron with the first neuron of my population X via the NSYNAPSE connection and among the neurons of X I'd to define STDP connections.

NOTE: I choosed to define the fictitious neuron because I noticed that if I define two separate populations with only one neuron for both and then I supply a constant input to the first by using the (deprecated) setConstInp, I recorded a spiking activity in the second population/neuron (after a while, of course), but what I obtained by considering the input current of pre-synaptic neuron as a variable (and therefore by avoiding to use the setConstInp function), changing it in the .cu file, was completely different, because the post-synaptic neuron didn't fire. For this reason, I would to use setConstInp for the fictitious neuron (and considering its current variable as a bias), because I think it can cause the activation of the first neuron of X and therefore the spiking activity of the second one.

What do you think? Any suggestions?

Thanks for your reply, of course.

**Comment by esinyavuz** [comment]
There is an example in the user manual explaining how sparse conectivity works: 

http://genn-team.github.io/genn/documentation/html/d5/d24/sectSynapseModels.html#subsect32

It is also explained in our paper (see Fig. 2):

http://www.nature.com/articles/srep18854

You can try yourself using the `gen_syns_sparse.cc` tool under `$GENN_PATH/userproject/tools`.
It generates both all-to-all and sparse connectivity arrays for a single synapse populaton given the number of presynaptic and postsynaptic neurons and their connection probability, mean strength and jitter. Then it writes them in binary files, so for a simple model in your head you can generate the connectivity and see what it looks like. Then all you have to do is to plug these arrays to the SparseProjection structure.

You can also check the `MBody_userdef_project` example which creates the connectivity as all-to-all but uses a helper function to translate it to sparse:

https://github.com/genn-team/genn/blob/master/userproject/MBody_userdef_project/model/map_classol.cc#L165

The helper tool is available under `$GENN_PATH/lib/include/sparseUtils.cc`

This example is the same as `MBody1_project` which uses built-in functions, but it re-defines the neuron and synapse populations and uses sparse connectivity instead of all-to-all.

I'm not sure how you implemented this but from what you explained I had the impression that you either defined the update in the learning in `simLearnPost` or wih a condition of spiking, or you did not copy the updated variables to the GPU. Have you tried to monitor the output of your presynaptic neuron?

By the way, you can implement it without defining a new population. You can check how the input current can be used as a variable in the Izhikevich example on the development branch:

https://github.com/genn-team/genn/blob/development/userproject/Izh_sparse_project/model/Izh_sparse.cc

(and compare it to the version in master branch which uses exlicit current input)

I hope this helps.

**Comment by Crypto1993** [comment]
How does the setSparseConnectivityFromDense function work?

By the way, my idea was essentialy related to the troubles I encountered in setting the "right" STDP effects, because if t_pre - t_post is the deltaTime on which the learning is based, how can it be possible if t_post is not defined (let us think a pre neuron connected to a post neuron; the first is firing, while the second is at rest).

**Comment by esinyavuz** [comment]
Check the link to the `MBody_userdef` example I linked above. The function call is:

`setSparseConnectivityFromDense(gPNKC, model.neuronN[0], model.neuronN[1], gpPNKC, &CPNKC);`

`gPNKC`: variable `g` of synapse `PNKC` (sparse) 
`model.neuronN[0]`: number of presynaptic neurons
`model.neuronN[1]`: number of postsynaptic neurons
`gpPNKC`: all-to-all array to be converted
`CPNKC`: sparseProjection object (generated by GeNN, in `yourmodel_CODE/runner.cc`)

You can find the function here:
https://github.com/genn-team/genn/blob/development/lib/include/sparseUtils.cc#L82

It goes over the all-to-all array, and once it finds a value which is higher than a threshold value, it adds a connection to the sparse connectivity structures. The threshold value is something low like 1e-20, defined by the `GENN_PREFERENCES::asGoodAsZero` value,  set in `$GENN_PATH/lib/include/global.h`

For spike timing, you can use built-in variables `sT_pre` and `sT_post` to refer to the spike times of the neurons, but it should also be possible to do it the way you did.

In our models we set the initial value of the variables that refer to spike timing (`sT` in our case, `t` in yours) to a very far away value such as -10000, to increase the delta time in the beginning. Once the postsynaptic neuron fires, it will be updated.

**Comment by jamesturner246** [comment]
Resolved - closing.
