### ISSUE TITLE
Compiling to dynamic library

### ISSUE THREAD

**Issue by kernfel** [genn-team/genn#99]
Back in version 2.1, it was possible to compile one's generated code into a dynamic library by adding a few flags in one's own makefile (`CXXFLAGS = -fPIC; NVCCFLAGS = -Xcompiler "-fPIC"; LINK_FLAGS = -shared`). In 2.2, this is no longer possible, because both the generated makefile and the makefile in genn/lib/ override the environment's CXXFLAGS/NVCCFLAGS, which means that neither runner.o nor libgenn.a can be compiled with -fPIC without manually changing files.

Since making dynamic libraries out of generated code has previously been considered a desirable feature (see https://github.com/genn-team/genn/issues/70), is there any call to provide such functionality again? I'd be happy to do the legwork for it, if the authors consider this a sensible idea.

**Comment by kernfel** [comment]
Just noticed that -fPIC is a requirement only for GNU, not Windows, so @spinang likely isn't concerned with this.

**Comment by tnowotny** [comment]
If this possibility was removed in 2.2 it was a side-effect of streamlining the compile process more generally. It would certainly be desirable to keep such options open if at all possible. @kernfel, do you have an idea how to bring it back with minor disruption of the code base?

**Comment by tnowotny** [comment]
PS: Happy for you to join the developer team if you're happy to do that.

**Comment by jamesturner246** [comment]
Yes, there's now a separate generated Makefile for all generated code, which currently doesn't support custom compile flags. Right now, it uses `GENN_PREFERENCES::optimizeCode` and `GENN_PREFERENCES::debugCode` to generate `-O3 -use_fast_math` and `-Oo -g -G` respectively.

I could add an option, say `GENN_PREFERENCES::[ cuda | cpp ]CompilerOptions`, to pass custom options to either compiler, which would cater to your needs.

Just curious, how come you are compiling a shared library from the generated code? Is it because you need to dynamically load and unload it at runtime? Else shared CUDA libs aren't that useful, since only one process can access  any given CUDA context (CUDA 'process').

**Comment by kernfel** [comment]
I've been compiling and loading/unloading models at runtime from within a GUI, the motivation being that I don't want to have to fiddle with console commands while I'm doing live experimental work. I realise that what I'm doing isn't exactly mainstream GeNN usage though, hence my hesitation.

I suppose adding the relevant flags into a GENN_PREFERENCES option would work if I linked libgenn.a into the main program. I do rather like using the userproject makefile, though (it's so nice and complete!)...

To keep that, I'd need an additional switch in genn-buildmodel.sh to compile a libgenn_SHARED.a (analogous to libgenn_CPU_ONLY.a). In the diff below, I'm also changing generateAll at compile time, although without reflecting this in the name (as for debug versions), as well as the userproject makefile to accept a SHARED parameter. This suits my needs, but may strike you as overkill... let me know what you think.

[shared1.diff.txt](https://github.com/genn-team/genn/files/385961/shared1.diff.txt)

**Comment by jamesturner246** [comment]
OK, but note that `GENN_PREFERENCES::compilerOptions` can be changed inside the modelDefinition file; you shouldn't need to include libgenn if you don't already need to.
